### ISSUE TITLE
Support go-redis V7.2.0

### ISSUE THREAD

**Issue by wantdrink** [bsm/redislock#10]
Hi there,

Since go-redis/redis v7.2.0 is stable now, using the latest go-redis with redislock will lead to error:

> Cannot use 'client' (type *redis.Client) as type RedisClient Type does not implement 'RedisClient' need method: ScriptExists(scripts ...string) *redis.BoolSliceCmd have method: ScriptExists(hashes ...string) *BoolSliceCmd 

Is there any plan to support this version?

Thanks.

**Comment by dim** [comment]
Closing in favour of #11

**Comment by wantdrink** [comment]
Cool. it works perfectly. Thanks @dim !
