### ISSUE TITLE
Support for multiple clients

### ISSUE THREAD

**Issue by pankaj-rapido** [bsm/redislock#14]
Redlock specification talks about multiple independent redis servers to do distributed locking. 

Does this library support that?

**Comment by dim** [comment]
No, this library works on top of https://pkg.go.dev/github.com/go-redis/redis/ which supports standard, failover and cluster clients. Multi-master distlocks are out of scope.

**Comment by pankaj-rapido** [comment]
Ok, the reason I asked is, because library title mentions it as `distributed locking implementation`
