### ISSUE TITLE
Generic Interface

### ISSUE THREAD

**Issue by dineshgowda24** [bsm/redislock#19]
The interface in the package is closely coupled with `github.com/go-redis/redis/`. In my application I use `https://github.com/gomodule/redigo` this package does not have return types like `redis.BoolSliceCmd`.

Suggestion can we make the interface more generic?

```
// RedisClient is a minimal client interface.
type RedisClient interface {
	SetNX(key string, value interface{}, expiration time.Duration) *redis.BoolCmd
	Eval(script string, keys []string, args ...interface{}) *redis.Cmd
	EvalSha(sha1 string, keys []string, args ...interface{}) *redis.Cmd
	ScriptExists(scripts ...string) *redis.BoolSliceCmd
	ScriptLoad(script string) *redis.StringCmd
}
```

**Comment by dim** [comment]
@dineshgowda24 sounds like https://github.com/go-redsync/redsync is what you are looking for
