### ISSUE TITLE
Add context param to all functions and methods that make calls to redis

### ISSUE THREAD

**Issue by yansal** [bsm/redislock#24]
Now that this package uses https://pkg.go.dev/github.com/go-redis/redis/v8 at version v8, would it be OK to add a `ctx context.Context` parameter to every functions and methods in this package that make calls to redis ?

It would enable passing a context to hooks in the redis package, see https://pkg.go.dev/github.com/go-redis/redis/v8#Hook.

I would be happy to send a PR if that's OK for you.

Thank you for considering.

**Comment by dim** [comment]
@yansal this is already happening, you can already pass a context as part of options. I'm happy to replace this with passing context explicitly and release a new major version if you create a PR. Please don't forget to update changelog too. Many thanks!!
