### ISSUE TITLE
Please Follow Semantic Import Versioning

### ISSUE THREAD

**Issue by swtch1** [bsm/redislock#26]
Thank you for this package.  My company uses it to maintain distributed locks. We appreciate your contribution, but would more appreciate it if your feature updates were backwards compatible. Changing the signature of methods causes an issue when the major version is not bumped because Go does not expect it, and we get build and import errors.  There's nothing wrong with moving to a v2 at some point.

**Comment by dim** [comment]
@swtch1 thanks, but we are following semantic versioning. We don't feel that this library is mature enough for v1 yet. After the change to the API, we have created a new release, bumping the version from v0.6 to v0.7 which is in line with semantic versioning guidelines for <1.0 versions. Apologies if this has caused issues for you.

**Comment by swtch1** [comment]
Thank you.  I get it, and you're right for making breaking changes under v1.  I think Go just expects breaking changes to be on a different import path and when they aren't it causes issues.  It's a bit of an annoyance when it happens, but we've been able to resolve it by just upgrading the library to the latest version everywhere.
