### ISSUE TITLE
Global locker object or local

### ISSUE THREAD

**Issue by smaheshs** [bsm/redislock#29]
Hi,

I have checked that having a global locker object or creating a new one at the point of acquiring a lock both works.

However what is the best practice that you would suggest, create globally or at the point of acquiring the lock.

Thanks.
Mahesh S.

**Comment by dim** [comment]
Sorry, there is no `Locker` object, just `Client` and `Lock`. You should obtain a fresh lock every time you need it. Calling `Refresh` is an option to extend the TTL but not much more.

**Comment by smaheshs** [comment]
Sorry, I went by the variable name. The client variable was named 'locker' and I referred to that only.

Could you please tell me the best practice for the `Client` object. Should it be at global scope or local to the scope where the lock is being obtained.

Thanks.

**Comment by dim** [comment]
You only ever need one instance, it is thread-safe and can create many locks. From a performance/allocation point if view it would be beneficial to initialise it only once, but that's really implementation specific and for you to decide.
