### ISSUE TITLE
A question about ttl

### ISSUE THREAD

**Issue by parchk** [bsm/redislock#34]
https://github.com/bsm/redislock/blob/97011e6af39ac0f8f2a2ee4d04cadc50a43d1f68/redislock.go#L64
https://github.com/bsm/redislock/blob/97011e6af39ac0f8f2a2ee4d04cadc50a43d1f68/redislock.go#L89-L91
Why is the deaaline here related to the value of ttl and not another option, if I want to keep blocking and waiting until the other party actively releases this lock, I find I have no way to implement this requirement.

**Comment by dim** [comment]
@parchk good point, could you please check #35

**Comment by artiomgiza** [comment]
Hi @dim 
Looks like this issue was not resolved ([PR](https://github.com/bsm/redislock/pull/35) is still open).

**Comment by dim** [comment]
@artiomgiza merged + tagged a new version

**Comment by kuilasaurav** [comment]
@artiomgiza this is the a scneario I intend to use
could you help me with an example or point me in the right direction to recreate it?
I don't understand how to obtain a lock without a TTL

**Comment by artiomgiza** [comment]
> @artiomgiza this is a scenario I intend to use could you help me with an example or point me in the right direction to recreate it? I don't understand how to obtain a lock without a TTL

@kuilasaurav If I understand correctly your question, it's not possible to create a lock without TTL (actually it's good thing:)
This [line](https://github.com/bsm/redislock/pull/35/files#diff-ce12e94e59df19d2c491ba721b88092178860cdafc30d0162cc3a3323b5c296cR65) shows us that if no deadline set - it will be taken from the `ttl` you pass into `Obtain(..., ttl, ...)` func.
In this case you can create `ctx` param (in the caller function) with any deadline you want.

> I don't understand how to obtain a lock without a TTL

If this is what is needed, you can pass `ttl` param of 10 years (so it will be the same as forewer = no ttl). 
But it feels a bit wrong to me.

Hope this helps...
