### ISSUE TITLE
Doesn't work with redis/v9

### ISSUE THREAD

**Issue by rv-nath** [bsm/redislock#46]
When  I have this code 
```go
rc := GetRedisClient()
locker  := redislock.New(rc)
```
And my redis helper file, uses redis v9 like below..
```go
package main

import (
  "github.com/ilyakaznacheev/cleanenv"
  "github.com/go-redis/redis/v9"
  "github.com/rs/zerolog/log"
)

 ...
 ...

func GetRedisClient() *redis.Client{

  if client == nil {
    //fmt.Println("Obtaining a connection to Redis...")
    log.Print("Obtaining connection to Redis...")
    client = redis.NewClient(&redis.Options{
      Addr: cfg.Addr,
      Password: cfg.Password,
      DB: cfg.DB,
    })
  } else {
    log.Print("Reusing connection to Redis...")
  }
  return client
}

```

Then, I get an error
cmd/app/game-controller.go:85:27: cannot use rc (variable of type *"github.com/go-redis/redis/v9".Client) as type redislock.RedisClient in argument to redislock.New:
        *"github.com/go-redis/redis/v9".Client does not implement redislock.RedisClient (wrong type for Eval method)
                have Eval(ctx context.Context, script string, keys []string, args ...interface{}) *"github.com/go-redis/redis/v9".Cmd
                want Eval(ctx context.Context, script string, keys []string, args ...interface{}) *"github.com/go-redis/redis/v8".Cmd
make: *** [makefile:8: build] Error 2

**Comment by dim** [comment]
Hi, the library is still working with [v8](https://github.com/bsm/redislock/blob/main/go.mod#L5) since v9 is only in beta. We will release a new/updated version shortly.

**Comment by dim** [comment]
See #47

**Comment by kamikazechaser** [comment]
Just a heads up. `go-redis v9` is not backward compatible with `redis v6` (https://github.com/go-redis/redis/issues/2222). I suggest putting a notice on the README wrt.
