### ISSUE TITLE
redis.Nil check for SetNX

### ISSUE THREAD

**Issue by pierrre** [bsm/redislock#6]
https://github.com/bsm/redislock/blob/b80b08c8989703908279cfb50782179de7fdd5f0/redislock.go#L98
Maybe I'm misunderstanding something, but why is the code checking `redis.Nil` for a call to `SetNX` ?
I thought that it was returned only for `Get`.
I don't see anything in the documentation about this.

**Comment by dim** [comment]
Valid point, I don't think it's needed. I think it's been added to be on the safe side. Happy to remove, could you please PR?

**Comment by pierrre** [comment]
As I said in #5 I'm not really a user of this library.
I'm just reporting an issue I noticed.

**Comment by dim** [comment]
Addressed in https://github.com/bsm/redislock/pull/7
