### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by liufengsoft** [bsm/redislock#67]
panic stack:

runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:260 (0x4500f5)
/usr/local/go/src/runtime/signal_unix.go:835 (0x4500c5)
/go/pkg/mod/github.com/bsm/redislock@v0.9.1/redislock.go:175 (0xb05410)

**Comment by dim** [comment]
@liufengsoft are you sure that you have a lock? could you please post the whole section of your code where you are obtaining it? 

It looks as if you are doing this:

```go
lock, err := client.Obtain(ctx, "mykey", time.Minute, nil)
defer lock.Release() // lock may be nil here

if err != nil {
  // handling errors after deferring Release is a source of panics
}
```

**Comment by liufengsoft** [comment]
Yes
`locker := gredis.NewRedisLock()
 lock, err := locker.Obtain(ctx, fmt.Sprintf("task_dispatch_%s", taskID), time.Second*5, &redislock.Options{
		RetryStrategy: redislock.LinearBackoff(500 * time.Millisecond), // always retry every 500 millisecond
})
// miss err check here. my fault.
defer func() {
		err = lock.Release(ctx)
}()
`
Tasks that take a very long time may cause a panic, and I suspect that the lock has expired automatically. But my code does not handle the err returned by locker.Obtain, which may be the root cause of this problem. If nil support is added to the lock and related err are return by the release method, the code will be more robust

**Comment by liufengsoft** [comment]
Wow, Too fast. Thanks.
