### ISSUE TITLE
Uncompatible with new version.

### ISSUE THREAD

**Issue by xiekeyi98** [bsm/redislock#9]
Thanks for this good repo.
Now I am trying to update the version get this:

```
cannot use redisClient (type *"github.com/go-redis/redis".Client) as type redislock.RedisClient in argument to redislock.New:
        *"github.com/go-redis/redis".Client does not implement redislock.RedisClient (wrong type for Eval method)
                have Eval(string, []string, ...interface {}) *"github.com/go-redis/redis".Cmd
                want Eval(string, []string, ...interface {}) *"github.com/go-redis/redis/v7".Cmd
```

**Comment by dim** [comment]
@xiekeyi98 you need to migrate from `import "github.com/go-redis/redis"` to `import "github.com/go-redis/redis/v7"

**Comment by xiekeyi98** [comment]
> github.com/go-redis/redis

Thanks for your kindly help.
Now go-redis/redis is only beta in v7 , and I use this repo update with `go get -u=patch`, then I got uncompatible behaviour.

Not offsensive , But I think it is not a good practice.

**Comment by dim** [comment]
Apologies, I didn't see that v7 is in beta. I will downgrade to v6

**Comment by dim** [comment]
Resolved, thanks for the report & explanation
